# ¿Qué es R? Instalando R y RStudio

## Definiendo R
R es un lenguaje de programación que fue lanzado de manera estable el año 2000 por Robert Gentleman y Ross Ihaka (1993) del Departamento de Estadística de la Universidad de Auckland (Nueva Zelanda), quienes se basaron en el lenguaje de programación S desarrollado en los laboratorios Bell de Estados Unidos (1970), con el fin prácticamente exclusivo de construir un lenguaje para el análisis estadístico. De acuerdo al *TIOBE programming community index (marzo de 2021)*, R ocupa el puesto 11 entre los lenguajes de programación más populares, toda una sorpresa para una herramienta que fue pensada solo para propósitos estadísticos. 
 
Habiendo dado esta breve definición de R, ahora nos enfocaremos en instalar R en nuestro computador. Luego de esto, utilizaremos la consola de R como una vulgar calculadora de para darle las primeras instrucciones y hacernos una idea muy general de cómo funciona y cuáles son los símbolos de algunas operaciones matemáticas muy básicas. Sin embargo, haremos esto muy sucintamente, ya que luego descargaremos RStudio, el cual es el entorno de desarrollo integrado más popular para interactuar con R y el que usaremos a lo largo de este curso. Cuando lleguemos a dicha subsección, revisaremos más detalles al respecto, por ahora vamos a instalar R. 
 
## Instalando R

Primero que todo, necesitamos instalar R en nuestro computador. Para esto debemos ir a la siguiente website: 

```{block, type='FOO'}
http://cran.r-project.org/
```


En la parte superior, aparecerá un cuadro con tres opciones diferentes de descarga según el sistema operativo que use tu computador (i.e., Windows, OS X o Linux). Dale clic a la opción que corresponda a tu caso. 

### R para Windows

A pesar de que la página de R no es particularmente “estética”, puedes fácilmente visualizar y clicar la opción de descarga para Windows [(“Download R for Windows”)](https://cran.r-project.org){target="_blank"}. Una vez hayas seleccionado este enlace, dale clic a “install R for the first time”. Esto te llevará finalmente a la página de descarga donde tienes que clicar el enlace que dice “Download R 4.0.5 for Windows (85 megabytes, 32/64 bit)” (o cual sea la versión que veas al momento de descargar R). Esto iniciará la descarga de un archivo, el cual tardará unos pocos minutos dependiendo de tu conexión a internet y otras variables. Ya descargado, haz doble clic para instalarlo y responde apropiadamente las preguntas que haga Windows para su instalación y ubicación. Seguir las opciones por defecto por lo general es una buena idea. Ahora ya teniendo instalado R en tu computador, puedes ir al menú de inicio y abrirlo.

### R para Mac

### R para Linux
