# Comandos Básicos en R

## R como una Simple Calculadora

Una de las primeras cosas que podemos hacer para comenzar a familiarizarnos con R es usarla como si fuera una simple calculadora. De esta manera, escribiremos los primeros comandos o instrucciones y obtendremos resultados conocidos a partir de nuestra experiencia con cálculos matemáticos adquiridos durante nuestra educación primaria. Nada intimidante la verdad. En la consola de R, podemos escribir `2 + 5` y luego apretar “*enter*”. Cuando escribimos `2 + 5` lo que hicimos fue escribir un **comando** y R ejecutará dicho comando. Lo que tu vas a ver en la consola de R corresponde a: 

```{r class.source="bg-danger", class.output="bg-warning"}
2 + 5
```

Ahora bien, este simple ejemplo nos servirá para explicar algunas cosas muy simples de R. El primer bloque de arriba (es decir, `2 + 5`) corresponde al comando o instrucciones que escribimos y el bloque de abajo es el *output* o salida de R, el cual nos muestra el resultado de la suma. En este bloque, aparecen dos *hashtags* o “*signos gatos*” (como le decimos en Chile), al lado `[1] `, el cual señala el número del output producido por R (y que por cierto nosotros no escribimos, sino fue producido por R) y al lado, finalmente, aparece el resultado de la sumatoria, es decir, `7`. *So far, so good!* (¡hasta ahora todo bien!).

En la tabla 1, puedes encontrar un resumen de algunas operaciones matemáticas básicas en R. 

```{=html}    
                              <center> <h3>Tabla 1 </h3> </center>
```
              
| Operación      | Símbolo u operador | Ejemplo  | Resultado |
|:----------------:|:------------------:|:--------:|:---------:|
|      Suma      |          +         |  `3 + 6` |    `9`    |
|      Resta     |          -         |  `6 - 2` |    `4`    |
| Multiplicación |          *         |  `5 * 8` |    `40`   |
|    División    |          /         | `21 / 7` |    `3`    |
|    Potencia    |          ^         |  `2 ^ 6` |    `64`   |

## Errores de Escritura o *typos* en R

Para interactuar con R, nuestras instrucciones deben ser claras y precisas. De este modo, R podrá realizar exactamente lo que nosotros le pidamos. Sin embargo, si no somos lo suficientemente claros y precisos, R no hará lo que le pidamos y nos dará algún mensaje de error de algún tipo. Y aceptémoslo, más temprano que tarde cometeremos un error de escritura en R, el cual será el inicio de muchos errores en el camino que emprendamos en el análisis de datos a través del uso de R. 
