# Glosario

**Atributos.** Los objetos en R pueden tener atributos.  Los atributos son como metadatos para el objeto. Estos metadatos pueden ser muy útiles ya que nos proporcionan información del objeto. Por ejemplo, los nombres de columna en un data frame nos proporcionan información de lo que contiene cada columna. Algunos ejemplos de atributos en objetos R son: *names*, *dimnames*, *dimensions* (en matrices, arrays), *class* (e.g. integer, numeric), *length*, u otros atributos/metadatos definidos por el usuario. Para acceder a los atributos de un objeto (si los hay), se utiliza la función `attributes()`. No todos los objetos contienen atributos.  En este ultimo caso, la función `attributes()` devolverá `NULL`.

**Data Frame.** Los data frames son utilizados en R para almacenar datos de tipo tabla. Es un tipo de objeto muy importante en R y utilizados ampliamente en modelado estadístico. Los data frames son representados como un tipo especial de lista donde cada elemento de la lista tiene que tener la misma longitud. Podemos considerar cada elemento de la lista como una columna y la longitud de cada elemento de la lista como el número de filas. A diferencia de las matrices, los data frames pueden almacenar diferentes clases de objetos en cada columna. Recordemos que los matrices debían tener cada elemento de la misma clase (e.g. todos enteros o todos numéricos).

**Entorno de Desarrollo Integrado.** Los entornos de Desarrollo, o *integrated development environment (IDE)* en inglés, son las herramientas con las cuales los programadores crean aplicaciones. En el caso de R, RStudio es un entorno de Desarrollo integrado. Un IDE consta de las siguientes herramientas: **1.	Editor**. Generalmente, se utilizan editores que colorean la sintaxis para ayudar al programador a comprender mejor el programa y detectar los errores más fácilmente. 
**2.	Compilador o intérprete**. Dependiendo del tipo de lenguaje utilizado (en nuestro caso R), se necesitará para ejecución el intérprete o el compilador para generar código ejecutable. 
**3.	Depurador**. Un buen depurador siempre tiene un intérprete detrás para ir ejecutando órdenes paso a paso, inspeccionar el valor de variables, etc.

**Factores**. Los factores son utilizados para representar categorías y pueden estar ordenadas o desordenadas. Podemos pensar en los factores como un vector de enteros en el que cada entero representa una etiqueta. Los factores son importantes en modelos estadísticos y se utilizan especialmente para modelar junto a funciones como `lm()` y `glm()`.

**Función.** Las funciones reúnen una secuencia de operaciones como un todo, almacenándola para su uso continuo. Las funciones proveen: (1) un nombre que podemos recordar y usar para invocarla; (2) una solución para la necesidad de recordar operaciones individuales; (3) un conjunto definido de *inputs* y *outputs* esperados. 

**Lenguaje de Programación R.** R es un entorno y lenguaje de programación con un enfoque al análisis estadístico. Se trata de uno de los lenguajes de programación más utilizados en investigación científica, siendo además muy popular en los campos de aprendizaje automático (*machine learning*), minería de datos, investigación biomédica, bioinformática y matemáticas financieras. A esto contribuye la posibilidad de cargar diferentes bibliotecas o paquetes con funcionalidades de cálculo y graficación.

**Listas.** Las listas son un tipo especial de vector que pueden contener objetos de diferentes clases. Las listas son una estructura de datos muy importante y ampliamente utilizada.

**Matrices.** Las matrices son vectores con un atributo denominado dimension. Este atributo que nos proporciona la dimensión de la matriz es en sí mismo un vector de tipo entero de longitud 2 (número de filas, número de columnas).

**Metadatos.** Los metadatos, literalmente *sobre datos*, son datos que describen otros datos. En general, un grupo de metadatos se refiere a un grupo de datos que describen el contenido informativo de un objeto al que se denomina recurso. El concepto de metadatos es análogo al uso de índices para localizar objetos en vez de datos. Por ejemplo, en una biblioteca se usan fichas que especifican autores, títulos, casas editoriales y lugares para buscar libros. Así, los metadatos ayudan a ubicar datos.

**Objetos en R.** R tiene cinco tipos básicos de objetos: character, numeric (número real), integer
complex, logical (True/False). El objeto más básico en R es un vector. Podemos crear vectores vacíos con la función `vector()`. Existe sólo una regla sobre los vectores en R:un vector sólo puede contener objetos de la misma clase. Pero, como en cualquier buena regla, las listas son una excepción. Una lista es representada como un vector pero puede contener objetos de diferentes clases. 

**Programación Orientada a Objetos.**La programación Orientada a Objetos (POO) se define como un paradigma de la programación, una manera de programar específica, donde se organiza el código en unidades denominadas clases, de las cuales se crean objetos que se relacionan entre sí para conseguir los objetivos de las aplicaciones.La POO es una forma especial de programar, más cercana a como expresaríamos las cosas en la vida real que otros tipos de programación.

**R Markdown.** *R Markdown*  fue diseñado para facilitar la replicabilidad del código y la descripción narrativa del proceso de análisis de datos en el mismo documento. De este modo, los resultados son automáticamente generados desde la misma fuente de código. *R Markdown* soporta una docena de formatos de salidas estáticas y dinámicas. 

**R Notebook.** *R Notebook* es un documento de *R Markdown* con pedazos o trozos de código que pueden ser ejecutados independiente e interactivamente, con la salida visible inmediatamente después del código o input. 

**RStudio.** Es un entorno de desarrollo integrado (IDE) para el lenguaje de programación R, dedicado a la computación estadística y gráficos. Incluye una consola, editor de sintaxis que apoya la ejecución de código, así como herramientas para el trazado, la depuración y la gestión del espacio de trabajo. RStudio está disponible para Windows, Mac y Linux o para navegadores conectados a RStudio Server o RStudio Server Pro (Debian / Ubuntu, RedHat / CentOS, y SUSE Linux). RStudio tiene la misión de proporcionar el entorno informático estadístico R. Permite un análisis y desarrollo para que cualquiera pueda analizar los datos con R.

**Valores Indefinidos.** Los valores indefinidos son indicados en R por `NA` o `NaN` para cualquier operación indefinida matematicamente.

**Vectores.** Los vectores en R son objetos de una única dimensión que puede contener datos numéricos, cadena de caracteres o datos lógicos, entre otros. Esencialmente son uno de los elementos básicos en la estructura de los datos en R. Pueden contener solo elementos de un solo tipo, aunque su tamaño podría ser ilimitado.