# Anexo 2: Respuesta a Ejercicios {- #anexo_2}

## Respuestas de Ejercicios de la Subsección 2.7.1 {-}

Ejercicio 1

```{r eval=FALSE}
head(dataset, 20)
```
Ejercicio 2

```{r eval=FALSE}
tail(dataset, 15)
```
Ejercicio 3

```{r eval=FALSE}
dataset$Nivel
```

Ejercicio 4

```{r eval=FALSE}
dataset[50:95, c("edad", "calificacion_5")]
```

Ejercicio 5

```{r eval=FALSE}
ejercicio_4 <- dataset[50:95, c("edad", "calificacion_5")]
```

Ejercicio 6

```{r eval=FALSE}
dim(ejercicio_4)
```

Ejercicio 7

```{r eval=FALSE}
subset(dataset, Nivel == 301 )
```

Ejercicio 8

```{r eval=FALSE}
subset(dataset, Nivel == 101 | Nivel == 201 | Nivel == 202)
```

Ejercicio 9

```{r eval=FALSE}
summary(dataset$promedio, na.rm = TRUE)
```

Ejercicio 10

```{r eval=FALSE}
promedio_preg_10 <- rowMeans(dataset[,5:7], na.rm=TRUE)
```

Ejercicio 11

```{r eval=FALSE}
table(dataset$Nivel)
```

Ejercicio 12

```{r eval=FALSE}
barplot(table(dataset$Nivel))
```

Ejercicio 13

```{r eval=FALSE}
plot(dataset$emociones_positivas, dataset$emociones_negativas)
```

Ejercicio 14

```{r eval=FALSE}
modelo_lineal <- lm(dataset$emociones_negativas ~ dataset$emociones_positivas, data = dataset)
plot(dataset$emociones_negativas, dataset$emociones_positivas)
abline(modelo_lineal, col = "blue")
```

Ejercicio 15
```{r eval=FALSE}
modelo_lineal 
```

## Respuestas de Ejercicios de la Subsección 3.7.1 {- #anexo_3_7_1}

Ejercicio 1

```{r eval=FALSE}
*File* →*New file* → *R Notebook* → "guardar como" `ejercicio_1`
```

Ejercicio 2

```{r eval=FALSE}
Lo que debería pasar es que los colores del texto han cambiado de color a lo largo del R Notebook. Esto significa que R no esta interpretando correctamente donde termina dicho trozo de código. Debido a esto, no es una buena idea agregar o eliminar guiones en esta parte del script porque va a estropear todo el formato del código escrito abajo. A todo esto, no olviden agregar nuevamente el guión al inicio del script (deben ser tres guiones). 
```