--- 
title: "Introducción al Análisis de Datos en Psicología usando R"
author: "Daniel Pérez Zapata"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introducción

Bienvenidas y bienvenidos a *Introducción al Análisis de Datos en Psicología usando R*. Este curso tiene como principal objetivo desarrollar habilidades básicas para realizar análisis de datos en psicología (o en cualquier otra disciplina aplicando la misma lógica general) usando el lenguaje de programación R. Primero que todo, me gustaría decir que para usar esta herramienta no hace falta ser un experto en programación, poseer conocimientos superlativos y una memoria sinigual para aprender todas las funcionalidades en R. Para eso existen las opciones de ayuda en R y el vasto universo de contenidos que habita en *google*. Mucho mejor es utilizar nuestros recursos cognitivos en conceptualizar adecuadamente nuestros problemas de investigación y de resolver dichos desafíos flexiblemente a través de R. Puedo dar fe de todo esto porque lo he leído en diferentes libros, blogs, lo he visto en un amplio número de videos en internet, he asistido a cursos presenciales y online de R, he conversado con colegas y amigos, pero, principalmente, porque yo mismo tengo este perfil.


Comencé a aprender sobre ciencia de datos utilizando R y Python (otro popular lenguaje de programación que, entre muchas cosas, sirve para el análisis de datos), hace prácticamente dos años. Obviamente, lo sigo aprendiendo día a día porque ambos lenguajes son universos inagotables y con fronteras en continua expansión gracias a sus mismos usuarios. Como la gran mayoría de personas que empiezan el camino del análisis de datos usando lenguajes de programación, en un comienzo estaba absolutamente perdido, no entendía por donde tenía que comenzar, o por qué tenia que aprender un montón de términos como *programación orientada a objetos*, *atributos*, *funciones*, etc. Ustedes se pueden imaginar lo desorientado y abrumado que me sentía sin conocimiento alguno de programación. Mirando en retrospectiva, este recurso online hubiera sido bastante útil para mi yo del pasado, considerando sobretodo mi formación y conocimientos en psicología. Para los no psicólogos, en casi todos los programas de estudios de pregrado y postgrado en psicología, no se contempla el aprendizaje de lenguajes de programación para el análisis de datos. De este modo, me parece que un libro de fácil lectura sobre R, basado en casos, problemas y/o investigaciones psicológicas, que entregue herramientas básicas para comenzar a ensuciarse las manos con el análisis de datos, es una muy buena idea y una excelente forma de invertir nuestro tiempo 🤓. 

Sin embargo, antes de seguir adelante, quizás la primera pregunta que deberíamos responder es: ¿por qué debería aprender a programar en R? No es una pregunta fácil de contestar, pero trataré de responderla tomando en cuenta lo que dicen algunos textos especializados sobre el tema y también a partir de mi propia experiencia. Probablemente, las razones más comunes y poderosas son porque R es gratis y de acceso abierto. Gratis es un concepto bastante auto explicativo y no es necesario ahondar en él (solo mencionar que R seguirá siendo gratis *per saecula saeculorum*, es decir, para siempre). Acceso abierto o de código abierto es algo menos obvio, pero tampoco difícil de entender. Simplemente significa que cualquier persona en el mundo puede contribuir a su desarrollo. Contrasta con lenguajes cerrados (comúnmente de uso comercial como *Windows* de Microsoft) en los cuales las personas no pueden libremente acceder al código base y de este modo contribuir a su desarrollo. 


Alguien podría pensar en este punto que ¿el desarrollo de R depende de personas con un gran espíritu prosocial que están dispuestas a desarrollar herramientas para que otras personas puedan utilizarlas sin pagar un peso o un dólar? La respuesta es básicamente: ¡Sí! Otros podrían pensar que esto dejaría a R a disposición de un grupo reducido de personas que se den el tiempo para trabajar desinteresadamente en estos proyectos y, por lo tanto, que sea un proceso bastante lento, repleto de errores y poco confiable. Afortunadamente para nosotros, la comunidad de R es bastante extensa (literalmente miles de personas alrededor del mundo), y existen más de 16,000 librerías de análisis de datos disponibles en R, y son bastantes confiables. Como uno podría esperar, hay librerías mejor desarrolladas que otras o algunas que alcanzado una madurez lo suficientemente altas que ya forman parte del flujo de trabajo cotidiano de muchos analistas de datos (como por ejemplo las librerías `dplyr`, `ggplot2`, por solo mencionar dos).
